const itemsArray = [
  {
    id: "1",
    name: "Laptop",
    details: "High-performance laptop with SSD",
    price: 1299.99,
    brand: "Dell",
    inStock: true,
  },
  {
    id: "2",
    name: "Smartphone",
    details: "Latest smartphone with dual cameras",
    price: 799.99,
    brand: "Samsung",
    inStock: true,
  },
  {
    id: "3",
    name: "Headphones",
    details: "Wireless noise-canceling headphones",
    price: 249.99,
    brand: "Sony",
    inStock: true,
  },
  {
    id: "4",
    name: "Coffee Maker",
    details: "Programmable coffee maker with grinder",
    price: 89.99,
    brand: "Keurig",
    inStock: false,
  },
  {
    id: "5",
    name: "Running Shoes",
    details: "Breathable running shoes with cushioned soles",
    price: 79.99,
    brand: "Nike",
    inStock: true,
  },
  {
    id: "6",
    name: "Backpack",
    details: "Water-resistant backpack with multiple compartments",
    price: 49.99,
    brand: "The North Face",
    inStock: true,
  },
  {
    id: "7",
    name: "Smartwatch",
    details: "Fitness tracker with heart rate monitor",
    price: 129.99,
    brand: "Fitbit",
    inStock: true,
  },
  {
    id: "8",
    name: "Gaming Console",
    details: "Next-gen gaming console with 4K graphics",
    price: 499.99,
    brand: "PlayStation",
    inStock: true,
  },
  {
    id: "9",
    name: "Desktop Monitor",
    details: "Ultra-wide monitor for productivity",
    price: 349.99,
    brand: "LG",
    inStock: true,
  },
  {
    id: "10",
    name: "Wireless Keyboard",
    details: "Slim and ergonomic wireless keyboard",
    price: 59.99,
    brand: "Logitech",
    inStock: true,
  },
];

module.exports = {
  itemsArray,
  // ... export other datasets
};
